### ISSUE TITLE
The error 'ModuleNotFoundError: No module named 'pytz'' happens during creating the project

### ISSUE THREAD

**Issue by adriana-shymoniak** [planeks/django-docker-boilerplate#2]
Tried to create a progect by using the ```$ django-admin startproject myproject --template 0.9.tar.gz -e py,html,md,yml -n start``` command.
The error is appeared:
 ```
ModuleNotFoundError: No module named 'pytz'
```

Used python 3.7.9 and pip 20.1.1 
Also used in another attempt 
python 3.8.6 and pip 20.1.1 

OS:
Ubuntu 18.04.5 LTS

Installing the pytz by using the ``` pip install pytz ``` command is not helped.

The Traceback:
```
Traceback (most recent call last):
  File "/home/adrianashymoniak/.local/bin/django-admin", line 10, in <module>
    sys.exit(execute_from_command_line())
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/commands/startproject.py", line 1, in <module>
    from django.core.management.templates import TemplateCommand
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/core/management/templates.py", line 16, in <module>
    from django.template import Context, Engine
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/template/__init__.py", line 44, in <module>
    from .engine import Engine
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/template/engine.py", line 7, in <module>
    from .base import Context, Template
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/template/base.py", line 61, in <module>
    from django.utils.formats import localize
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/utils/formats.py", line 7, in <module>
    from django.utils import dateformat, datetime_safe, numberformat
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/utils/dateformat.py", line 21, in <module>
    from django.utils.timezone import get_default_timezone, is_aware, is_naive
  File "/home/adrianashymoniak/.local/lib/python3.7/site-packages/django/utils/timezone.py", line 11, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

**Comment by olehkorkh-planeks** [comment]
@adriana-shymoniak I think that something is going wrong with your virtual environment. When you use `startproject` command the boilerplate files are not launching. You need to create your virtual environment correctly.
